services:
  animated-artworks:
    container_name: apple-music-animated-artworks
    image: ghcr.io/m8tec/apple-music-animated-artworks:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      CACHE_FILE_PATH: /app/data/cache_database.json
    restart: always

  animated-artwork-downloader:
    container_name: animated-artwork-downloader
    image: ghcr.io/m8tec/animated-artwork-downloader:latest
    depends_on:
      - animated-artworks
    environment:
      SyncConfig__LibraryPath: ${LIBRARY_PATH:-/music}
      SyncConfig__ArtworkApiUrl: ${ARTWORK_API_URL:-http://animated-artworks:8080}
      SyncConfig__DelayBetweenApiRequestsMs: ${DELAY_BETWEEN_API_REQUESTS_MS:-2000}
      SyncConfig__MinVariantResolution: ${MIN_VARIANT_RESOLUTION:-1000}
      SyncConfig__WebpQuality: ${WEBP_QUALITY:-50}
    volumes:
      - ${MUSIC_LIBRARY_PATH:?Set MUSIC_LIBRARY_PATH in .env}:${LIBRARY_PATH:-/music}
      - ${CACHE_DIRECTORY:-./data}:/data
    restart: unless-stopped
